AppName: voting-app
replicaCount: 1

image:
  repository: Dockerfile
  pullPolicy: IfNotPresent
  tag: "latest"

containerPort: 80
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: NodePort
  port: 80
  nodePort: 30007

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: Dockerfile
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []


resources: {}


autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 50

nodeSelector: {}

tolerations: []

affinity: {}